### ISSUE TITLE
This solution is deprecated 

### ISSUE THREAD

**Issue by shinesoftware** [Vinai/module-current-product-example#2]
Hi Vinai,

I have noticed that the latest version 2.3.4 of magento has removed the catalog_controller_product_init. Have do you a replacement of that event? or better could we replace it with a plugin?

Regards

**Comment by Vinai** [comment]
Well, you can now use a plugin instead of the event.
I strongly dislike Magento removing events, i think it is an awful mistake.
It will increase coupling and backward incompatible breaks, making developing with Magento even more expensive and dull.

**Comment by Vinai** [comment]
Oh, there also still is the event `catalog_controller_product_init_after` that could be used instead.

**Comment by Vinai** [comment]
@shinesoftware I just checked the code in this example repo, and it indeed uses the event `catalog_controller_product_init_after`, so it will still work with Magento 2.3.4.
What are you talking about?

**Comment by shinesoftware** [comment]
@Vinai so there is a problem in the changelog of Magento 2 because I read: https://github.com/magento/magento2/blob/2.4-develop/CHANGELOG.md

2.0.0.0-dev46
=============
* Various improvements:
  * Removed some events (plugins must be used instead):
     * catalog_controller_product_init

How have you used the plugin ? Have you a clue?

**Comment by Vinai** [comment]
@shinesoftware Look in the [events.xml](https://github.com/Vinai/module-current-product-example/blob/master/etc/frontend/events.xml#L3) file and see the module uses the `catalog_controller_product_init_after` event, not the `catalog_controller_product_init` event you are talking about.

Then look at the `\Magento\Catalog\Helper\Product` (in [2.3.4](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Helper/Product.php#L470-L473)) and see, it does indeed dispatch the event.

The changelog section you are talking about is about was for a pre-release development version of version Magento 2.0.0 (2.0.0.0-dev46 to be exact - see your own reply above), not Magento 2.3.4.

So you are talking about changes from 6 years ago, and about an event that this example module doesn't use and never has used.

So, what is your point?

**Comment by shinesoftware** [comment]
@Vinai thanks for the clarification! I have assumed that the catalog_controller_product_init_after was the "magic" _after _before that Magento core offers to all the controllers. Thanks.

Btw the point is: do a developer build an entire module only to get the product selected? Is there a way to get it by a simple plugin? If yes, how do you have created it? thanks

**Comment by Vinai** [comment]
I often used something like this in my modules. In Magento 2 it's quite common to have to create a dozen files to accomplish something simple.
¯\\_(ツ)_/¯
